config/routes.rb
Rails.application.routes.draw do
  resources :vehicle_types
  resources :vehicle_brands
  get "print_index" => "vehicle_brands#print_index", as: "print_index"
  get 'pages/home'
  root to:'pages#home'
  devise_for :users, controllers: {
        registrations: 'users/registrations',
        sessions: 'users/sessions'
      }
  resources :users
  resources :roles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :api, defaults: {format: :json} do
    resources :vehicle_brands
  end
end

app/models/vehicle_brand.rb
class VehicleBrand < ApplicationRecord
    mount_uploader :image, ImageUploader

    def self.to_csv(options = {})
        CSV.generate(options) do |csv|
            csv << ["Nama", "Tanggal dibuat"]
            all.each do |vehicle_brand|
                csv << [ vehicle_brand.name, vehicle_brand.created_at.strftime("%d-%B-%Y") ]
            end
        end
    end

end

app/controllers/api/vehicle_brands_controller.rb
class Api::VehicleBrandsController < Api::ApplicationController
  before_action :set_vehicle_brand, only: %i[ show edit update destroy capitalize_font]

  # skip_before_action :verify_authenticity_token
  after_action :capitalize_font, only: [:create]

  # GET /vehicle_brands or /vehicle_brands.json
  def index
    @search = VehicleBrand.ransack(params[:q])
    @vehicle_ransack = @search.result(distinct: true)
    @vehicle_brands = @vehicle_ransack.page(params[:page]).per(5).order(name: :asc)
    render json:{result: @vehicle_brands, status:'success', message: 'data berhasil dibaca'}
    # authorize @vehicle_brands
  end

  def print_index
    if params[:q]
      @search = VehicleBrand.ransack(params[:q])
      @vehicle_brands = @search.result(distinct: true)
    else  
      @vehicle_brands = VehicleBrand.all
    end
    # render json: @vehicle_brands
    respond_to do |format|
      format.csv {send_data @vehicle_brands.to_csv, :filename => 'data_vehicle.csv', :disposition => 'inline', :type => "multipart/related"}
    end  
  end    

  # GET /vehicle_brands/1 or /vehicle_brands/1.json
  def show
  end

  # GET /vehicle_brands/new
  def new
    @vehicle_brand = VehicleBrand.new
  end

  # GET /vehicle_brands/1/edit
  def edit
    authorize @vehicle_brand
  end

  # POST /vehicle_brands or /vehicle_brands.json
  def create
    @vehicle_brand = VehicleBrand.new(vehicle_brand_params)

      if @vehicle_brand.save
          render json: {:status => 'success', message: 'Data Berhasil diinput', result: @vehicle_brand}
      else
          render json: {:status => 'failed', message: 'Data tidak Berhasil diinput'}
      end
  end

  # PATCH/PUT /vehicle_brands/1 or /vehicle_brands/1.json
  def update
      if @vehicle_brand.update(vehicle_brand_params)
        render json: {:status => 'success', message: 'Data Berhasil updated', result: @vehicle_brand}
      else
        render json: {:status => 'failed', message: 'Data tidak Berhasil updated'}
      end
  end

  # DELETE /vehicle_brands/1 or /vehicle_brands/1.json
  def destroy
    @vehicle_brand.destroy

    render json: {:status => 'success', message: 'Data Berhasil dihapus'}
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle_brand
      @vehicle_brand = VehicleBrand.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def vehicle_brand_params
      params.require(:vehicle_brand).permit(:name, :image)
    end

    def capitalize_font
      @vehicle_brand_update = @vehicle_brand.update_attributes(:name => @vehicle_brand.name.upcase)
    end
end

app/controllers/vehicle_brands_controller.rb
class VehicleBrandsController < ApplicationController
  before_action :set_vehicle_brand, only: %i[ show edit update destroy ]

  # GET /vehicle_brands or /vehicle_brands.json
  def index
    @search = VehicleBrand.ransack(params[:q])
    @vehicle_ransack = @search.result(distinct: true)
    @vehicle_brands = @vehicle_ransack.page(params[:page]).per(5).order(name: :asc)

    @api_example = HTTParty.get('https://alita.massindo.com/api/v1/areas')
    authorize @vehicle_brands
  end

  def print_index
    if params[:q]
      @search = VehicleBrand.ransack(params[:q])
      @vehicle_brands = @search.result(distinct: true)
    else  
      @vehicle_brands = VehicleBrand.all
    end
    # render json: @vehicle_brands
    respond_to do |format|
      format.csv {send_data @vehicle_brands.to_csv, :filename => 'data_vehicle.csv', :disposition => 'inline', :type => "multipart/related"}
    end  
  end    

  # GET /vehicle_brands/1 or /vehicle_brands/1.json
  def show
  end

  # GET /vehicle_brands/new
  def new
    @vehicle_brand = VehicleBrand.new
  end

  # GET /vehicle_brands/1/edit
  def edit
    authorize @vehicle_brand
  end

  # POST /vehicle_brands or /vehicle_brands.json
  def create
    @vehicle_brand = VehicleBrand.new(vehicle_brand_params)

    respond_to do |format|
      if @vehicle_brand.save
        format.html { redirect_to vehicle_brands_path, notice: "Vehicle brand was successfully created." }
        format.json { render :show, status: :created, location: @vehicle_brand }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @vehicle_brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicle_brands/1 or /vehicle_brands/1.json
  def update
    respond_to do |format|
      if @vehicle_brand.update(vehicle_brand_params)
        format.html { redirect_to vehicle_brand_url(@vehicle_brand), notice: "Vehicle brand was successfully updated." }
        format.json { render :show, status: :ok, location: @vehicle_brand }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @vehicle_brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicle_brands/1 or /vehicle_brands/1.json
  def destroy
    @vehicle_brand.destroy

    respond_to do |format|
      format.html { redirect_to vehicle_brands_url, notice: "Vehicle brand was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle_brand
      @vehicle_brand = VehicleBrand.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def vehicle_brand_params
      params.require(:vehicle_brand).permit(:name, :image)
    end
end

app/helpers/vehicle_brands_helper.rb
module VehicleBrandsHelper
end

app/views/vehicle_brands/_form.html.erb
<%= form_with(model: vehicle_brand, local: true) do |form| %>
  <% if vehicle_brand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vehicle_brand.errors.count, "error") %> prohibited this vehicle_brand from being saved:</h2>

      <ul>
      <% vehicle_brand.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :logo %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vehicle_brands/edit.html.erb
<h1>Editing Vehicle Brand</h1>

<%= render 'form', vehicle_brand: @vehicle_brand %>

<%= link_to 'Show', @vehicle_brand %> |
<%= link_to 'Back', vehicle_brands_path %>

app/views/vehicle_brands/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vehicle Brands</h1>

<%= search_form_for @search do |f| %>

  # Search if the name field contains...
  <%= f.label :name_cont %>
  <%= f.search_field :name_cont %>
  <%= f.label :dibuat_lebih_dari %>
  <%= f.date_field :created_at_gt %>
  <%= f.label :kurang_dari %>
  <%= f.date_field :created_at_lt %>

  <%= f.submit %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>logo</th>
      <th>created</th>
      <th>update</th>
      <th>selisih</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vehicle_brands.each do |vehicle_brand| %>
      <tr>
        <td><%= vehicle_brand.name %></td>
        <% if vehicle_brand.image.present? %>
        <td><a href="<%=vehicle_brand.image_url%>" target="_blank">
          <%= image_tag(vehicle_brand.image_url, style:"height:40px; width:40px;")%>
        </a></td>
        <% else %>
          <td>-</td>  
        <% end %>
        <td><%= vehicle_brand.created_at.strftime("%d-%B-%Y") %></td>
        <td><%= vehicle_brand.updated_at.strftime("%d-%B-%Y") %></td>
        <td><%= TimeDifference.between(vehicle_brand.created_at, Time.now).humanize %></td>
        <td><%= link_to 'Show', vehicle_brand %></td>
        <td><%= link_to 'Edit', edit_vehicle_brand_path(vehicle_brand), target: :_blank %></td>
        <td><%= link_to 'Destroy', vehicle_brand, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= paginate @vehicle_brands %>

<%= link_to 'New Vehicle Brand', new_vehicle_brand_path %>
<br/>
<% if params[:q] %>
<%= link_to "export csv", print_index_path(q: {created_at_gt: params[:q]["created_at_gt"], created_at_lt: params[:q]["created_at_lt"], name_cont: params[:q]["name_cont"]}, format:"csv")%>
<% else %>
<%= link_to "export csv", print_index_path(format:"csv")%>
<% end %>

<br>
<br>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Name</th>
      <th>created</th>
    </tr>
  </thead>

  <tbody>

    <% @api_example['result'].each do |area| %> 
      <tr> 
      <td> <%= area['code'] %> </td>
      <td> <%= area['name'] %> </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/vehicle_brands/new.html.erb
<h1>New Vehicle Brand</h1>

<%= render 'form', vehicle_brand: @vehicle_brand %>

<%= link_to 'Back', vehicle_brands_path %>

app/views/vehicle_brands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @vehicle_brand.name %>
</p>

<%= link_to 'Edit', edit_vehicle_brand_path(@vehicle_brand) %> |
<%= link_to 'Back', vehicle_brands_path %>