config/routes.rb
Rails.application.routes.draw do
  resources :vehicle_types
  resources :vehicle_brands
  get "print_index" => "vehicle_brands#print_index", as: "print_index"
  get 'pages/home'
  root to:'pages#home'
  devise_for :users, controllers: {
        registrations: 'users/registrations',
        sessions: 'users/sessions'
      }
  resources :users
  resources :roles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :api, defaults: {format: :json} do
    resources :vehicle_brands
  end
end

app/controllers/vehicle_types_controller.rb
class VehicleTypesController < ApplicationController
  before_action :set_vehicle_type, only: %i[ show edit update destroy ]

  # GET /vehicle_types or /vehicle_types.json
  def index
    @vehicle_types = VehicleType.all
  end

  # GET /vehicle_types/1 or /vehicle_types/1.json
  def show
  end

  # GET /vehicle_types/new
  def new
    @vehicle_type = VehicleType.new
  end

  # GET /vehicle_types/1/edit
  def edit
  end

  # POST /vehicle_types or /vehicle_types.json
  def create
    @vehicle_type = VehicleType.new(vehicle_type_params)

    respond_to do |format|
      if @vehicle_type.save
        format.html { redirect_to vehicle_type_url(@vehicle_type), notice: "Vehicle type was successfully created." }
        format.json { render :show, status: :created, location: @vehicle_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @vehicle_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicle_types/1 or /vehicle_types/1.json
  def update
    respond_to do |format|
      if @vehicle_type.update(vehicle_type_params)
        format.html { redirect_to vehicle_type_url(@vehicle_type), notice: "Vehicle type was successfully updated." }
        format.json { render :show, status: :ok, location: @vehicle_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @vehicle_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicle_types/1 or /vehicle_types/1.json
  def destroy
    @vehicle_type.destroy

    respond_to do |format|
      format.html { redirect_to vehicle_types_url, notice: "Vehicle type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle_type
      @vehicle_type = VehicleType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def vehicle_type_params
      params.require(:vehicle_type).permit(:name, :vehicle_brand_id)
    end
end

app/helpers/vehicle_types_helper.rb
module VehicleTypesHelper
end

app/views/vehicle_types/_form.html.erb
<%= form_with(model: vehicle_type, local: true) do |form| %>
  <% if vehicle_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vehicle_type.errors.count, "error") %> prohibited this vehicle_type from being saved:</h2>

      <ul>
      <% vehicle_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :vehicle_brand_id %>
    <%= form.text_field :vehicle_brand_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vehicle_types/edit.html.erb
<h1>Editing Vehicle Type</h1>

<%= render 'form', vehicle_type: @vehicle_type %>

<%= link_to 'Show', @vehicle_type %> |
<%= link_to 'Back', vehicle_types_path %>

app/views/vehicle_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vehicle Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Vehicle brand</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vehicle_types.each do |vehicle_type| %>
      <tr>
        <td><%= vehicle_type.name %></td>
        <td><%= vehicle_type.vehicle_brand %></td>
        <td><%= link_to 'Show', vehicle_type %></td>
        <td><%= link_to 'Edit', edit_vehicle_type_path(vehicle_type) %></td>
        <td><%= link_to 'Destroy', vehicle_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vehicle Type', new_vehicle_type_path %>

app/views/vehicle_types/new.html.erb
<h1>New Vehicle Type</h1>

<%= render 'form', vehicle_type: @vehicle_type %>

<%= link_to 'Back', vehicle_types_path %>

app/views/vehicle_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @vehicle_type.name %>
</p>

<p>
  <strong>Vehicle brand:</strong>
  <%= @vehicle_type.vehicle_brand %>
</p>

<%= link_to 'Edit', edit_vehicle_type_path(@vehicle_type) %> |
<%= link_to 'Back', vehicle_types_path %>